/* eslint-disable camelcase */
import { TUnadaptedFilm } from '../types/films';

export const dataBase: TUnadaptedFilm[] = [
  {
    id: '0',
    film_info: {
      title: 'Laziness On Himself',
      alternative_title: 'A Tale Of A Little Bird Who Bought Himself',
      total_rating: 5.1,
      poster: 'images/posters/the-great-flamarion.jpg',
      age_rating: 6,
      director: 'Tom Ford',
      writers: ['Brad Bird'],
      actors: [
        'Takeshi Kitano',
        'Al Pacino',
        'Gary Oldman',
        'Michael Caine',
        'Matt Damon',
        'Cillian Murphy',
        'Morgan Freeman ',
        'Brad Pitt',
        'Edward Norton',
        'Harrison Ford',
      ],
      release: {
        date: '2015-07-04T04:17:59.135Z',
        release_country: 'Germany',
      },
      runtime: 135,
      genre: ['Family', 'Sci-Fi', 'Action'],
      description:
        'Oscar-winning film, true masterpiece where love and death are closer to heroes than their family, from the creators of timeless classic "Nu, Pogodi!" and "Alice in Wonderland".',
    },
    user_details: {
      watchlist: false,
      already_watched: true,
      watching_date: '2022-04-16T09:06:43.293Z',
      favorite: false,
    },
    comments: ['1335657', '1335658', '1335659', '1335660', '1335661'],
  },
  {
    id: '1',
    film_info: {
      title: 'A Man Of The Room',
      alternative_title: 'Raiders Who Himself',
      total_rating: 7.2,
      poster: 'images/posters/sagebrush-trail.jpg',
      age_rating: 6,
      director: 'Alejandro Gonsales Inarritu',
      writers: [
        'Robert Rodrigues',
        'Hayao Miazaki',
        'Quentin Tarantino',
        'Robert Zemeckis',
      ],
      actors: ['Michael Caine'],
      release: {
        date: '2017-09-20T04:30:10.447Z',
        release_country: 'China',
      },
      runtime: 68,
      genre: ['Animation'],
      description:
        'Oscar-winning film, true masterpiece where love and death are closer to heroes than their family, a film about a journey that heroes are about to make in finding themselves, with the best fight scenes since Bruce Lee.',
    },
    user_details: {
      watchlist: false,
      already_watched: true,
      watching_date: '2022-06-05T09:06:43.294Z',
      favorite: true,
    },
    comments: ['1335662', '1335663', '1335664', '1335665'],
  },
  {
    id: '2',
    film_info: {
      title: 'A Man Who Saw The Carpet',
      alternative_title: 'A Little Pony Who Stole The Floor',
      total_rating: 7.6,
      poster: 'images/posters/the-great-flamarion.jpg',
      age_rating: 21,
      director: 'Chrostopher Nolan',
      writers: ['Stephen Spielberg', 'Takeshi Kitano'],
      actors: [
        'Takeshi Kitano',
        'Edward Norton',
        'Brad Pitt',
        'Leonardo DiCaprio',
        'Robert De Niro',
      ],
      release: {
        date: '1999-01-25T01:09:55.602Z',
        release_country: 'Spain',
      },
      runtime: 118,
      genre: ['Thriller', 'Sci-Fi', 'Family', 'Drama'],
      description:
        'Oscar-winning film, a war drama about two young people, from the creators of timeless classic "Nu, Pogodi!" and "Alice in Wonderland", a film about a journey that heroes are about to make in finding themselves.',
    },
    user_details: {
      watchlist: true,
      already_watched: true,
      watching_date: '2022-11-22T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335666', '1335667', '1335668', '1335669'],
  },
  {
    id: '3',
    film_info: {
      title: 'A Man Within Themselves',
      alternative_title: 'A Shark In The Storm',
      total_rating: 5.8,
      poster: 'images/posters/made-for-each-other.png',
      age_rating: 21,
      director: 'Quentin Tarantino',
      writers: [
        'Stephen King',
        'Robert Zemeckis',
        'Brad Bird',
        'Robert Rodrigues',
      ],
      actors: [
        'Michael Caine',
        'Edward Norton',
        'Morgan Freeman ',
        'Christian Bale',
        'Brad Pitt',
        'Ralph Fiennes',
        'Robert De Niro',
        'Harrison Ford',
      ],
      release: {
        date: '1996-07-19T09:35:08.013Z',
        release_country: 'Finland',
      },
      runtime: 118,
      genre: ['Adventure', 'Thriller'],
      description:
        'a war drama about two young people, from the creators of timeless classic "Nu, Pogodi!" and "Alice in Wonderland".',
    },
    user_details: {
      watchlist: false,
      already_watched: true,
      watching_date: '2022-08-05T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335670', '1335671', '1335672', '1335673', '1335674'],
  },
  {
    id: '4',
    film_info: {
      title: 'Guest Who Sold Us',
      alternative_title: 'A Shark Who Saw The Storm',
      total_rating: 9,
      poster: 'images/posters/the-man-with-the-golden-arm.jpg',
      age_rating: 6,
      director: 'Clint Eastwood',
      writers: ['Brad Bird'],
      actors: [
        'Edward Norton',
        'Brad Pitt',
        'Harrison Ford',
        'Michael Caine',
        'Matt Damon',
      ],
      release: {
        date: '2016-07-04T20:00:32.690Z',
        release_country: 'France',
      },
      runtime: 160,
      genre: ['Sci-Fi', 'Action', 'Family'],
      description:
        'Oscar-winning film, a war drama about two young people, true masterpiece where love and death are closer to heroes than their family, with the best fight scenes since Bruce Lee.',
    },
    user_details: {
      watchlist: false,
      already_watched: true,
      watching_date: '2022-02-27T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335675', '1335676', '1335677', '1335678', '1335679'],
  },
  {
    id: '5',
    film_info: {
      title: 'Raiders Who The Storm',
      alternative_title: 'A Shark Who Saw Him',
      total_rating: 9.6,
      poster: 'images/posters/popeye-meets-sinbad.png',
      age_rating: 21,
      director: 'Akira Kurosawa',
      writers: ['Robert Zemeckis'],
      actors: [
        'Ralph Fiennes',
        'Al Pacino',
        'Tom Hanks',
        'Harrison Ford',
        'Gary Oldman',
        'Robert De Niro',
        'Edward Norton',
        'Leonardo DiCaprio',
        'Michael Caine',
        'Brad Pitt',
      ],
      release: {
        date: '2005-10-26T07:42:13.157Z',
        release_country: 'China',
      },
      runtime: 178,
      genre: ['Family', 'Thriller', 'Adventure', 'Drama', 'Comedy'],
      description: 'with the best fight scenes since Bruce Lee.',
    },
    user_details: {
      watchlist: true,
      already_watched: true,
      watching_date: '2022-03-01T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335680', '1335681', '1335682', '1335683'],
  },
  {
    id: '6',
    film_info: {
      title: 'Happiness On The Void',
      alternative_title: 'Country Without The Wall',
      total_rating: 6.3,
      poster: 'images/posters/santa-claus-conquers-the-martians.jpg',
      age_rating: 21,
      director: 'Akira Kurosawa',
      writers: ['Hayao Miazaki', 'Takeshi Kitano'],
      actors: [
        'Robert De Niro',
        'Brad Pitt',
        'Al Pacino',
        'Ralph Fiennes',
        'Takeshi Kitano',
        'Leonardo DiCaprio',
        'Morgan Freeman ',
        'Michael Caine',
        'Christian Bale',
      ],
      release: {
        date: '2011-03-01T13:12:39.752Z',
        release_country: 'Italy',
      },
      runtime: 111,
      genre: ['Drama', 'Sci-Fi', 'Family'],
      description:
        'Oscar-winning film, a war drama about two young people, true masterpiece where love and death are closer to heroes than their family, with the best fight scenes since Bruce Lee.',
    },
    user_details: {
      watchlist: true,
      already_watched: true,
      watching_date: '2022-11-22T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335684', '1335685', '1335686', '1335687'],
  },
  {
    id: '7',
    film_info: {
      title: 'Friends In The Wall',
      alternative_title: 'Pioneers Within Us',
      total_rating: 4.3,
      poster: 'images/posters/the-dance-of-life.jpg',
      age_rating: 18,
      director: 'Tom Ford',
      writers: [
        'Stephen Spielberg',
        'Hayao Miazaki',
        'Robert Zemeckis',
        'Stephen King',
      ],
      actors: [
        'Edward Norton',
        'Tom Hanks',
        'Leonardo DiCaprio',
        'Ralph Fiennes',
      ],
      release: {
        date: '1995-05-14T08:50:21.534Z',
        release_country: 'Germany',
      },
      runtime: 129,
      genre: ['Family', 'Animation', 'Comedy', 'Action'],
      description:
        'Oscar-winning film, a war drama about two young people, from the creators of timeless classic "Nu, Pogodi!" and "Alice in Wonderland", a film about a journey that heroes are about to make in finding themselves, with the best fight scenes since Bruce Lee.',
    },
    user_details: {
      watchlist: false,
      already_watched: false,
      watching_date: null,
      favorite: false,
    },
    comments: [
      '1335688',
      '1335689',
      '1335690',
      '1335691',
      '1335692',
      '1335693',
    ],
  },
  {
    id: '8',
    film_info: {
      title: 'A Tale Of A Little Bird Who Bought The Room',
      alternative_title: 'Happiness Who Stole Him',
      total_rating: 6.3,
      poster: 'images/posters/the-man-with-the-golden-arm.jpg',
      age_rating: 0,
      director: 'Tom Ford',
      writers: ['Martin Scorsese'],
      actors: [
        'Gary Oldman',
        'Christian Bale',
        'Morgan Freeman ',
        'Brad Pitt',
        'Tom Hanks',
        'Edward Norton',
        'Leonardo DiCaprio',
        'Takeshi Kitano',
        'Cillian Murphy',
      ],
      release: {
        date: '2023-06-22T02:45:53.601Z',
        release_country: 'Italy',
      },
      runtime: 124,
      genre: ['Thriller', 'Animation', 'Action', 'Sci-Fi'],
      description:
        'true masterpiece where love and death are closer to heroes than their family, from the creators of timeless classic "Nu, Pogodi!" and "Alice in Wonderland", a film about a journey that heroes are about to make in finding themselves, with the best fight scenes since Bruce Lee.',
    },
    user_details: {
      watchlist: false,
      already_watched: true,
      watching_date: '2022-08-06T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335694', '1335695', '1335696', '1335697', '1335698'],
  },
  {
    id: '9',
    film_info: {
      title: 'A Shark On The Carpet',
      alternative_title: 'A Tale Of A Little Bird Within The Darkness',
      total_rating: 8,
      poster: 'images/posters/the-man-with-the-golden-arm.jpg',
      age_rating: 18,
      director: 'Alejandro Gonsales Inarritu',
      writers: ['Martin Scorsese', 'Brad Bird', 'Stephen King'],
      actors: [
        'Matt Damon',
        'Brad Pitt',
        'Ralph Fiennes',
        'Tom Hanks',
        'Takeshi Kitano',
        'Michael Caine',
        'Edward Norton',
      ],
      release: {
        date: '2010-12-23T03:49:34.135Z',
        release_country: 'Germany',
      },
      runtime: 98,
      genre: ['Adventure', 'Sci-Fi'],
      description:
        'a war drama about two young people, true masterpiece where love and death are closer to heroes than their family, from the creators of timeless classic "Nu, Pogodi!" and "Alice in Wonderland", a film about a journey that heroes are about to make in finding themselves.',
    },
    user_details: {
      watchlist: false,
      already_watched: true,
      watching_date: '2022-07-16T09:06:43.294Z',
      favorite: false,
    },
    comments: ['1335699', '1335700', '1335701', '1335702'],
  },
];
